/**
 * Sudoku
 * 
 * Copyright (c) 2014-2020 Denis Meyer
 */
package de.calltopower.sudoku.gui;

import java.awt.event.KeyEvent;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import de.calltopower.sudoku.util.Constants;

public class About extends JDialog {

    private static final long serialVersionUID = -3892524398331742833L;

    private static final Logger LOGGER = LogManager.getLogger(About.class);

    /**
     * Creates new form About
     *
     * @param owner
     */
    public About(JFrame owner) {
        super(owner);

        LOGGER.debug("Initializing components");
        initComponents();
        URL imgURL = getClass().getClassLoader().getResource(Constants.IMAGE_ICON);
        if (imgURL != null) {
            this.label_image.setText("");
            ImageIcon icon = new ImageIcon(imgURL);
            this.label_image.setIcon(icon);
            this.setIconImage(icon.getImage());
        } else {
            LOGGER.error("Could not load image file '" + Constants.IMAGE_ICON + "'");
        }
        this.label_version.setText(Constants.APP_VERSION);

        this.setLocationRelativeTo(null);

        button_ok.requestFocus();

        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        label_image = new javax.swing.JLabel();
        label_sudoku = new javax.swing.JLabel();
        label_version_str = new javax.swing.JLabel();
        label_version = new javax.swing.JLabel();
        label_copyright_str = new javax.swing.JLabel();
        label_copyright = new javax.swing.JLabel();
        button_ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(321, 220));
        setMinimumSize(new java.awt.Dimension(321, 220));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setPreferredSize(new java.awt.Dimension(251, 140));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        label_image.setText("Sudoku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weighty = 1.0;
        jPanel1.add(label_image, gridBagConstraints);

        label_sudoku.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        label_sudoku.setText("Sudoku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel1.add(label_sudoku, gridBagConstraints);

        label_version_str.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        label_version_str.setText("Version");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(label_version_str, gridBagConstraints);

        label_version.setText("v1.0.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(label_version, gridBagConstraints);

        label_copyright_str.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        label_copyright_str.setText("Copyright");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(label_copyright_str, gridBagConstraints);

        label_copyright.setText("2014-2020 Denis Meyer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(label_copyright, gridBagConstraints);

        button_ok.setText("Ok");
        button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_okActionPerformed(evt);
            }
        });
        button_ok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                button_okKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel1.add(button_ok, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_okActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_button_okActionPerformed
        LOGGER.debug("Disposing UI");
        this.dispose();
    }// GEN-LAST:event_button_okActionPerformed

    private void button_okKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_button_okKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            LOGGER.debug("Disposing UI");
            this.dispose();
        }
    }// GEN-LAST:event_button_okKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ok;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_copyright;
    private javax.swing.JLabel label_copyright_str;
    private javax.swing.JLabel label_image;
    private javax.swing.JLabel label_sudoku;
    private javax.swing.JLabel label_version;
    private javax.swing.JLabel label_version_str;
    // End of variables declaration//GEN-END:variables

}
